name: Copy&Modification
on: 
  workflow_dispatch:
#  schedule:
#    - cron: 0 16 * * *
jobs:
    Copy&Modification:
        runs-on: ubuntu-18.04
        steps:
          - name: Checkout repo
            uses: actions/checkout@v2
          - name: Download files needed
            run: |
              mkdir -p /opt/shaolin-kongfu/zq/ && mkdir -p /opt/shaolin-kongfu/jc/
              git clone "https://github.com/shaolin-kongfu/js_scripts.git" "/opt/shaolin-kongfu/js_scripts/"
          - name: Modify files
            run: |
              find /opt/shaolin-kongfu/js_scripts/zq -name "*.json" | xargs -I {} cp {} /opt/shaolin-kongfu/zq/
              find /opt/shaolin-kongfu/js_scripts/ -name "*jc*.json" | xargs -I {} cp {} /opt/shaolin-kongfu/jc/
              find /opt/shaolin-kongfu/zq/ -type f | xargs -I {} sed -i 's#raw.githubusercontent.com#ghproxy.com/https://raw.githubusercontent.com#g' {}
              find /opt/shaolin-kongfu/jc/ -type f | xargs -I {} sed -i 's#raw.githubusercontent.com#ghproxy.com/https://raw.githubusercontent.com#g' {}
          - name: Send Back
            run:
              cp -f /opt/shaolin-kongfu/zq/* "${GITHUB_WORKSPACE}/shaolin-kongfu/"
          - name: Push
          - uses: mikeal/publish-to-github-action@master
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              BRANCH_NAME: 'main' #optional defaults to master

            
            
